development:
  amqp_url: amqp://localhost:5672/
  api_url: http://localhost:3000
  api_version: 0_5
  proxy: ""

test:
  amqp_url: amqp://localhost:5672/
  api_url: http://localhost:3000
  api_version: 0_5
  proxy: ""

cucumber:
  amqp_url: amqp://localhost:5672/
  api_url: http://localhost:3000
  api_version: 0_5
  proxy: ""
