development:
  api_url: http://localhost:3000
  api_version: 0_5
  proxy: ""

test:
  api_url: http://localhost:3000
  api_version: 0_5
  proxy: ""

cucumber:
  api_url: http://localhost:3000
  api_version: 0_5
  proxy: ""