development:
  adapter: mysql
  username: root
  password:
  host: localhost
  port: 3306
  database: warehouse_two_development

test: &test
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: warehouse_two_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
