name: CI docker

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - "README.md"
    tags:
      - uat-*
      - release-*
      - v*
env:
  IMAGE_NAME: ${{ github.repository }}/${{ github.event.repository.name }}

jobs:
  build_and_test_job:
    runs-on: ubuntu-18.04
    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: null
          MYSQL_DATABASE: unified_warehouse_test
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: >-
          docker build .
          --file Dockerfile
          --tag docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
      - name: Run Rubocop against the image
        run: >-
          docker run--env DBHOST=mysql --env DBPORT=3306  --network host 
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rubocop
      - name: Create EWH testing database
        run: >-
          docker run--env DBHOST=mysql --env DBPORT=3306  --network host 
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rake db:setup
      - name: Run tests against the image
        run: >-
          docker run--env DBHOST=mysql --env DBPORT=3306  --network host 
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/} 
          bundle exec rspec
      - name: Login to regitry
        run: >-
          docker login
          -u ${{ github.actor }}
          -p ${{ secrets.GITHUB_TOKEN }}
          docker.pkg.github.com
      - name: Publish image with image tag being either develop/master/<tag_name>
        run: >-
          docker push
          docker.pkg.github.com/${IMAGE_NAME}:${GITHUB_REF##*/}
